# Generated by Django 6.0.5 on 2026-05-26 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('computadora', '🖥️ Computadora'), ('monitor', '🖥️ Monitor'), ('teclado', '⌨️ Teclado'), ('mouse', '🖱️ Mouse'), ('router', '📡 Router'), ('impresora', '🖨️ Impresora'), ('mobiliario', '🪑 Mobiliario'), ('otro', '📦 Otro')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('operativo', '✅ 100% Operativo'), ('parcial', '⚠️ Parcialmente Operativo'), ('dañado', '🔧 Dañado/Reparación'), ('obsoleto', '📦 Obsoleto/Desincorporado')], default='operativo', max_length=20)),
                ('ubicacion', models.CharField(help_text='Estación, oficina, almacén', max_length=100)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('mensual', '📅 Mensual'), ('trimestral', '📅 Trimestral'), ('semestral', '📅 Semestral'), ('anual', '📅 Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Auditoría Programada',
                'verbose_name_plural': 'Auditorías Programadas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HallazgoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_fisica', models.IntegerField(blank=True, null=True)),
                ('estado_fisico', models.CharField(blank=True, choices=[('operativo', '✅ 100% Operativo'), ('parcial', '⚠️ Parcialmente Operativo'), ('dañado', '🔧 Dañado/Reparación'), ('obsoleto', '📦 Obsoleto/Desincorporado')], max_length=20, null=True)),
                ('observaciones', models.TextField()),
                ('fecha_hallazgo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('docena', 'Docena'), ('paquete', 'Paquete'), ('metro', 'Metro'), ('litro', 'Litro'), ('gramo', 'Gramo')], default='unidad', max_length=20)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Stock mínimo para alerta')),
                ('stock_maximo', models.IntegerField(default=100, help_text='Stock máximo recomendado')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación en el almacén', max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_teorica', models.IntegerField()),
                ('estado_teorico', models.CharField(blank=True, choices=[('operativo', '✅ 100% Operativo'), ('parcial', '⚠️ Parcialmente Operativo'), ('dañado', '🔧 Dañado/Reparación'), ('obsoleto', '📦 Obsoleto/Desincorporado')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', '📥 Entrada - Compra'), ('salida', '📤 Salida - Uso'), ('ajuste', '🔧 Ajuste Manual'), ('devolucion', '🔄 Devolución'), ('perdida', '⚠️ Pérdida/Merma')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField(help_text='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(help_text='Stock después del movimiento')),
                ('motivo', models.TextField(blank=True, help_text='Razón del movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_teorica', models.IntegerField(blank=True, null=True)),
                ('cantidad_fisica', models.IntegerField(blank=True, null=True)),
                ('variacion', models.IntegerField(blank=True, help_text='Diferencia: teórico - físico', null=True)),
                ('estado_teorico', models.CharField(blank=True, choices=[('operativo', '✅ 100% Operativo'), ('parcial', '⚠️ Parcialmente Operativo'), ('dañado', '🔧 Dañado/Reparación'), ('obsoleto', '📦 Obsoleto/Desincorporado')], max_length=20, null=True)),
                ('estado_fisico', models.CharField(blank=True, choices=[('operativo', '✅ 100% Operativo'), ('parcial', '⚠️ Parcialmente Operativo'), ('dañado', '🔧 Dañado/Reparación'), ('obsoleto', '📦 Obsoleto/Desincorporado')], max_length=20, null=True)),
                ('justificacion', models.CharField(choices=[('uso_administrativo', '📋 Uso Administrativo (actas, reportes)'), ('falla_tecnica', '🔧 Falla Técnica (atasco, daño)'), ('perdida', '⚠️ Pérdida/Desincorporación'), ('robo', '🚨 Robo/Extravió'), ('error_registro', '📝 Error en registro'), ('otro', '📌 Otro')], max_length=50)),
                ('detalle_justificacion', models.TextField(blank=True)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, default=0, help_text='Costo estimado para reponer', max_digits=10)),
                ('fecha_conciliacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.activofijo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='inventario.auditoriaprogramada')),
            ],
        ),
    ]
