# Generated by Django 6.0.5 on 2026-07-18 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('sublimacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.activofijo'),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='inventario.auditoriaprogramada'),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='conciliado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hallazgoauditoria',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.activofijo'),
        ),
        migrations.AddField(
            model_name='hallazgoauditoria',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='inventario.auditoriaprogramada'),
        ),
        migrations.AddField(
            model_name='hallazgoauditoria',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='hallazgoauditoria',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='conciliacioninventario',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='inventarioteorico',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.activofijo'),
        ),
        migrations.AddField(
            model_name='inventarioteorico',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_teorico', to='inventario.auditoriaprogramada'),
        ),
        migrations.AddField(
            model_name='inventarioteorico',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='pedido_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sublimacion.pedido'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
