# Generated by Django 6.0.5 on 2026-05-28 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alertastock_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', '🔐 Inicio de Sesión'), ('logout', '🚪 Cierre de Sesión'), ('crear', '➕ Crear Registro'), ('editar', '✏️ Editar Registro'), ('eliminar', '🗑️ Eliminar Registro'), ('cambiar_estado', '🔄 Cambiar Estado'), ('pago', '💰 Registro de Pago'), ('abono', '💵 Registro de Abono'), ('inventario_entrada', '📥 Entrada de Inventario'), ('inventario_salida', '📤 Salida de Inventario'), ('inventario_ajuste', '🔧 Ajuste de Inventario'), ('exportar', '📎 Exportar Reporte'), ('imprimir', '🖨️ Imprimir'), ('otro', '📌 Otro')], max_length=30)),
                ('modulo', models.CharField(help_text='Módulo donde se realizó la acción', max_length=50)),
                ('descripcion', models.TextField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('registro_nombre', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
    ]
