# Generated by Django 6.0.5 on 2026-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en dólares (USD)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en Bs (calculado automáticamente)', max_digits=10),
        ),
    ]
