# Generated by Django 6.0.5 on 2026-07-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del cliente')),
                ('id_cliente', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID / RIF del cliente')),
                ('direccion_cliente', models.TextField(blank=True, null=True, verbose_name='Dirección del cliente')),
                ('cantidad', models.IntegerField(default=1)),
                ('especificaciones', models.TextField(blank=True, help_text='Color, talla, diseño específico')),
                ('estado', models.CharField(choices=[('pendiente', '📋 Pendiente'), ('diseño', '🎨 En Diseño'), ('produccion', '🖨️ En Producción'), ('listo', '✅ Listo para Entregar'), ('entregado', '🎁 Entregado'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Total en Bs', max_digits=8)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio_usd_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario en USD al momento del pedido', max_digits=8)),
                ('tasa_usada', models.DecimalField(decimal_places=2, default=0, help_text='Tasa de cambio Bs/USD usada al momento del pedido', max_digits=10)),
                ('archivo_diseno', models.FileField(blank=True, null=True, upload_to='disenos/', verbose_name='Archivo de diseño')),
                ('notas_produccion', models.TextField(blank=True, help_text='Parámetros de producción: temperatura, tiempo, presión, etc.', null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='Taza', help_text='Ej: Taza, Camisa, Gorra, Llavero, Termo...', max_length=50)),
                ('precio_usd', models.DecimalField(decimal_places=2, default=0, help_text='Precio en dólares (USD) - se usará para calcular el precio en Bs según la tasa del día', max_digits=8)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, help_text='Precio en Bs (calculado automáticamente según la tasa de cambio)', max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Stock mínimo para alerta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
