# Generated by Django 6.0.5 on 2026-05-28 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='Taza', help_text='Ej: Taza, Camisa, Gorra, Llavero, Termo...', max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Stock mínimo para alerta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('cantidad', models.IntegerField(default=1)),
                ('especificaciones', models.TextField(blank=True, help_text='Color, talla, diseño específico')),
                ('estado', models.CharField(choices=[('pendiente', '📋 Pendiente'), ('diseño', '🎨 En Diseño'), ('produccion', '🖨️ En Producción'), ('listo', '✅ Listo para Entregar'), ('entregado', '🎁 Entregado'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublimacion.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='sublimacion.pedido')),
            ],
        ),
    ]
