# Generated by Django 6.0.5 on 2026-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublimacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='archivo_diseno',
            field=models.FileField(blank=True, null=True, upload_to='disenos/', verbose_name='Archivo de diseño'),
        ),
    ]
