# Generated by Django 6.0.5 on 2026-06-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublimacion', '0002_pedido_archivo_diseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notas_produccion',
            field=models.TextField(blank=True, help_text='Parámetros de producción: temperatura, tiempo, presión, etc.', null=True),
        ),
    ]
