# Generated by Django 6.0.5 on 2026-07-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublimacion', '0003_pedido_notas_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='telefono',
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección del cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cliente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID / RIF del cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del cliente'),
        ),
    ]
