# Generated by Django 6.0.5 on 2026-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublimacion', '0004_remove_pedido_telefono_pedido_direccion_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_usd_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario en USD al momento del pedido', max_digits=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tasa_usada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tasa de cambio Bs/USD usada al momento del pedido', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en dólares (USD) - se usará para calcular el precio en Bs según la tasa del día', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, help_text='Total en Bs', max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en Bs (calculado automáticamente según la tasa de cambio)', max_digits=8),
        ),
    ]
