# Generated by Django 6.0.5 on 2026-06-19 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo de rechazo si fue denegado', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha sido verificado por un administrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
