# Generated by Django 6.0.5 on 2026-07-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_avatar_usuario_fecha_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('dark', '🌙 Oscuro'), ('light', '☀️ Claro')], default='dark', max_length=10, verbose_name='Tema preferido'),
        ),
    ]
