# Generated by Django 6.0.5 on 2026-05-28 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0001_initial'),
        ('sublimacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estacion', '🖥️ Uso de PC'), ('sublimacion_pedido', '🎨 Pedido Completo de Sublimación'), ('sublimacion_abono', '💰 Abono de Sublimación'), ('papeleria', '📄 Papelería'), ('insumo', '📦 Venta de Insumo'), ('otros', '📌 Otros')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', '💵 Efectivo'), ('transferencia', '🏦 Transferencia Bancaria'), ('pago_movil', '📱 Pago Móvil'), ('tarjeta', '💳 Tarjeta de Débito/Crédito'), ('mixto', '🔄 Mixto (Varios métodos)')], default='efectivo', max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sublimacion.pedido')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estaciones.sesionpc')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
    ]
