# Generated by Django 6.0.5 on 2026-05-28 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', '🔐 Inicio de Sesión'), ('logout', '🚪 Cierre de Sesión'), ('crear', '➕ Crear Registro'), ('editar', '✏️ Editar Registro'), ('eliminar', '🗑️ Eliminar Registro'), ('cambiar_estado', '🔄 Cambiar Estado'), ('pago', '💰 Registro de Pago'), ('abono', '💵 Registro de Abono'), ('iniciar_sesion_pc', '🖥️ Iniciar Sesión en PC'), ('finalizar_sesion_pc', '⏹️ Finalizar Sesión en PC'), ('exportar', '📎 Exportar Reporte'), ('imprimir', '🖨️ Imprimir'), ('otro', '📌 Otro')], max_length=30)),
                ('modulo', models.CharField(help_text='Módulo donde se realizó la acción', max_length=50)),
                ('descripcion', models.TextField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registro_id', models.IntegerField(blank=True, help_text='ID del registro afectado', null=True)),
                ('registro_nombre', models.CharField(blank=True, help_text='Nombre/identificador del registro', max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
    ]
