# Generated by Django 6.0.5 on 2026-07-18 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        ('sublimacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='pedido_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sublimacion.pedido'),
        ),
    ]
