# Generated by Django 6.0.5 on 2026-07-18 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0001_initial'),
        ('reportes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='sesion_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estaciones.sesionpc'),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='actualizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
