# Generated by Django 6.0.5 on 2026-06-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_auditoria_registro_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
