# Generated by Django 6.0.5 on 2026-07-12 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_delete_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('pc_hora', '🖥️ PC por Hora'), ('sublimacion_taza', '🎨 Taza Sublimada'), ('sublimacion_camiseta', '👕 Camiseta Sublimada'), ('sublimacion_gorra', '🧢 Gorra Sublimada'), ('sublimacion_termo', '🫖 Termo Sublimado'), ('impresion_bn', '📄 Impresión B/N'), ('impresion_color', '🎨 Impresión Color'), ('fotocopia_bn', '📋 Fotocopia B/N'), ('fotocopia_color', '📋 Fotocopia Color'), ('insumo_venta', '📦 Venta de Insumo'), ('servicio_extra', '🔧 Servicio Extra')], max_length=30, unique=True)),
                ('nombre_mostrar', models.CharField(help_text='Nombre amigable para mostrar', max_length=100)),
                ('precio_usd', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio de Servicio',
                'verbose_name_plural': 'Precios de Servicios',
                'ordering': ['servicio'],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Tasa de cambio Bs/USD', max_digits=10)),
                ('fuente', models.CharField(default='Manual', help_text='API o Manual', max_length=50)),
                ('actualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
            },
        ),
    ]
