# Generated by Django 6.0.5 on 2026-07-18 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de PC')),
                ('estado', models.CharField(choices=[('libre', '🟢 Libre'), ('ocupada', '🔴 Ocupada'), ('mantenimiento', '🟡 Mantenimiento')], default='libre', max_length=20)),
                ('precio_hora', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio de uso')),
                ('tiempo_acumulado', models.IntegerField(default=0, verbose_name='Tiempo acumulado (minutos)')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SesionPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('tipo_cobro', models.CharField(choices=[('acumulado_horas', 'Cobro acumulado por horas libres'), ('tiempo_fijo', 'Pago por tiempo específico')], default='acumulado_horas', max_length=30)),
                ('duracion_programada_minutos', models.IntegerField(blank=True, null=True)),
                ('termina_en', models.DateTimeField(blank=True, help_text='Se usa para cerrar automáticamente en cobro por tiempo fijo', null=True)),
                ('tiempo_minutos', models.IntegerField(default=0)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil')], max_length=30, null=True)),
                ('cerrada_automaticamente', models.BooleanField(default=False)),
                ('cliente_nombre', models.CharField(blank=True, max_length=100)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estaciones.estacion')),
            ],
            options={
                'verbose_name': 'Sesión de PC',
                'verbose_name_plural': 'Sesiones de PC',
                'ordering': ['-hora_inicio'],
            },
        ),
    ]
