# Generated by Django 6.0.5 on 2026-07-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionpc',
            name='tipo_cobro',
            field=models.CharField(choices=[('acumulado_horas', 'Cobro acumulado por horas libres'), ('tiempo_fijo', 'Pago por tiempo específico')], default='acumulado_horas', max_length=30),
        ),
    ]
