"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
import dj_database_url  # Necesario para producción con Render, pero también funciona local

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# ===== SEGURIDAD =====
# ============================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-03upwc(g)3@01u&%md)34c69)^*vyoh@_z3h*_=uarc*8(14z7')

# SECURITY WARNING: don't run with debug turned on in production!
# <-- CAMBIO: DEBUG es True por defecto en local (a menos que se defina False en variable de entorno)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# <-- CAMBIO: ALLOWED_HOSTS con valores locales válidos
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# <-- CAMBIO: CSRF_TRUSTED_ORIGINS debe tener un esquema. Para local, valores por defecto válidos.
# Si se define variable de entorno, se añaden a esta lista base.
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
# Si tienes variable de entorno, la procesamos correctamente
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    extra = [url.strip() for url in os.environ.get('CSRF_TRUSTED_ORIGINS').split(',') if url.strip()]
    CSRF_TRUSTED_ORIGINS.extend(extra)

# ============================================================
# ===== APLICACIONES INSTALADAS =====
# ============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'estaciones',
    'sublimacion',
    'inventario',
    'reportes',
    'asistente',
]

# ============================================================
# ===== MIDDLEWARE =====
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Útil para producción, no molesta en local
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ============================================================
# ===== TEMPLATES =====
# ============================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ============================================================
# ===== BASE DE DATOS (CONFIGURACIÓN PARA RENDER) =====
# ============================================================
# <-- CAMBIO: Para local, si no hay DATABASE_URL, usa SQLite (por defecto)
# Si quieres usar PostgreSQL local, define DATABASE_URL en tu entorno.
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}

# ============================================================
# ===== VALIDACIÓN DE CONTRASEÑAS =====
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================
# ===== AUTENTICACIÓN Y USUARIO PERSONALIZADO =====
# ============================================================
AUTH_USER_MODEL = 'usuarios.Usuario'
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.VerificacionBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ============================================================
# ===== CONFIGURACIÓN DE EMAIL =====
# ============================================================
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Cyber Comunal <noreply@cybercomunal.com>')

# ============================================================
# ===== INTERNACIONALIZACIÓN =====
# ============================================================
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True

# ============================================================
# ===== ARCHIVOS ESTÁTICOS Y MEDIA =====
# ============================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # Útil en producción

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============================================================
# ===== SEGURIDAD (PRODUCCIÓN) =====
# ============================================================
# <-- CAMBIO: Estas configuraciones solo se aplican si DEBUG es False (producción)
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ============================================================
# ===== LOGGING (OPCIONAL) =====
# ============================================================
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'INFO',
#     },
# }